Daniel d/tsk 3777 zoom integration
blinkops/blink-http pull request #109
Opened 2022-05-12 14:52 UTC by DanielDinsh

2022-05-12 17:44 UTC, blink-daniel requested changes

2022-05-12 17:44 UTC, blink-daniel commented on plugins/zoom/zoom.go
> +
remove space

2022-05-12 17:44 UTC, blink-daniel commented on plugins/zoom/zoom.go
> +		return errors.New("the provided connection don't contain API Key")
doesn't

2022-05-12 17:44 UTC, blink-daniel commented on plugins/zoom/zoom.go
> +		return errors.New("the provided connection don't contain Secret Key")
doesn't

2022-05-12 17:44 UTC, blink-daniel commented on plugins/zoom/zoom.go
> +		ExpiresAt: time.Now().Unix() + 3600,
In general, don't use hardcoded numbers/strings with a special meaning/context/

Replace to -
time.Now().Add(tokenExpiryDuration)

where tokenExpiryDuration should be constant var, 
e.g const tokenExpiryDuration = time.Hour

2022-05-12 17:44 UTC, blink-daniel commented on plugins/zoom/zoom.go
> +	apiKey, hasApiKey := conn["API_KEY"]
hasAPIKey - in go, the convention is to use UPPER CAPS for acronyms such e.g API, URL

2022-05-12 17:44 UTC, blink-daniel commented on plugins/zoom/zoom.go
> +		return errors.New(fmt.Sprintf("the provided credentials are invalid: %v", err))
replace errors.New(fmt.Sprintf) with fmt.Errorf() for new formatted errors

2022-05-12 17:44 UTC, blink-daniel commented on plugins/zoom/mask.yaml
> +  icon_uri: https://app.dev.blinkops.com/assets/images/Icons/Companies/Company/XL/Tenable.svg
Zoom.svg

2022-05-12 17:44 UTC, blink-daniel commented on plugins/zoom/zoom.go
> +		ExpiresAt: time.Now().Unix() + 3000,
if there is a specific reason why you chose 50 minutes, please comment in code

2022-05-12 17:44 UTC, blink-daniel commented on plugins/zoom/mask.yaml
> +        alias: User Info Email
If you've chosen to alias this, make this more readable, e.g just "Email" instead "User Info Email"

2022-05-12 17:44 UTC, blink-daniel commented on plugins/zoom/mask.yaml
> +        alias: User Info Type
same as above

2022-05-13 13:55 UTC, ozhey commented on plugins/zoom/zoom.go
> +		ExpiresAt: time.Now().Unix() + 3600,
Also, as far as I understand this token is used once and then thrown away, so let's give it a much shorter expiry, like 30 seconds

2022-05-13 13:57 UTC, ozhey commented on plugins/zoom/mask.yaml
> +        alias: User Info Email
By the way, Im not 100% about it but I think that it automatically takes the last part after the __, so if you didnt use an alias at all, it would still call it 'Email'

2022-05-15 06:49 UTC, blink-daniel approved these changes

2022-05-15 11:38 UTC, merged