Tsk 3203 gen integrations readme
blinkops/blink-http pull request #114
Opened 2022-05-24 15:45 UTC by IdoGafi

2022-05-26 14:27 UTC, blink-daniel requested changes
few minor changes, also regarding error handling make sure to follow https://github.com/blinkops/style/blob/main/style.md#error-wrapping

2022-05-26 14:27 UTC, blink-daniel commented on components/docs/markdown.go
> +	row = row + 2 // extra lines for title & line
row += 2

2022-05-26 14:27 UTC, blink-daniel commented on cmd/docs/main.go
> +		return err
wrap the error with some context, e.g "handle file %s" with errors.Wrap

2022-05-26 14:27 UTC, blink-daniel commented on cmd/docs/main.go
> +		return err
wrap the error with some context, e.g "handle file %s" with errors.Wrap

2022-05-26 14:27 UTC, blink-daniel commented on components/docs/docs.go
> +		return err
same here, add context to the error

2022-05-26 14:27 UTC, blink-daniel commented on components/docs/docs.go
> +		log.Fatal(err)
intentional instead of simply returning an error?

2022-05-26 14:27 UTC, blink-daniel commented on components/docs/markdown.go
> +	return ioutil.WriteFile(filename, []byte(docToExport), os.ModePerm)
add error handling so we'll know the context of the error, e.g

if err := ioutil.WriteFile(filename, []byte(docToExport), os.ModePerm); err != nil {
   return errors.Wrap(err, "export to file")
}

return nil

2022-05-26 14:27 UTC, blink-daniel commented on components/docs/markdown.go
> +	return m
FYI - the only time we have to use new() is for passing primtives pointers, such as new(int)

2022-05-29 14:52 UTC, IdoGafi commented on components/docs/docs.go
> +		log.Fatal(err)
Yep, if something is not working write we would like not to generate the docs at all instead of creating a broken one

2022-05-31 07:01 UTC, blink-daniel approved these changes

2022-05-31 07:01 UTC, merged