Ron/tsk 3326 sumo logic integration
blinkops/blink-http pull request #131
Opened 2022-06-08 20:43 UTC by Mono2202

2022-06-08 21:09 UTC, ozhey reviewed
Great job!
I recommend adding .idea to your global .gitignore file (if you don't have one, add one :-) ), we don't want to commit such files
And of course we'll talk tomorrow about which actions to keep

2022-06-08 21:09 UTC, ozhey commented on gen/content/metadata.yaml
> +name: ""
What's that? I think it can be removed

2022-06-08 21:09 UTC, ozhey commented on plugin.yaml
> +    reference: rapid7
good catch

2022-06-08 21:09 UTC, ozhey commented on plugins/sumo-logic/mask.yaml
> +    REQUEST_URL:
This is going to have to change (probably tomorrow) to `api_address` due to a migration we are doing (to make everything use the same named convention, lowercase & snakecase)
@IdoGafi is working on it, sync with him

2022-06-08 21:09 UTC, ozhey commented on plugins/sumo-logic/sumo-logic.go
> +	requestUrl, ok := connection.Data["REQUEST_URL"]
same comment here about `api_address` & also use the constant from `consts` package

2022-06-08 22:36 UTC, blink-daniel requested changes
### Great job there, impressive how fast you got up to speed :)

Few more comment-

1. your generated content folder contain all actions from the open api file. looking into your mask file, I see that you only want to add one action, so I guess the other actions are from a previous attempt to call the make named-actions cmd? if that's the case, delete the gen folder and re-run the make so only the one action you wanted will be added. also, the gen/content/metadata.yaml file was probably generated from a failed attempt earlier due to padding issues in your mask file, so re-running the make should solve this as well. in the end, make sure that 0003_actions folder contain only the actions that we want to expose to the user from the sumo logic api.
2. Please use your real name as your git author name - think of someone else seeing that "Mono" committed a change wondering "who is this guy ?" :)

2022-06-09 08:15 UTC, blink-daniel approved these changes

2022-06-09 08:18 UTC, blink-daniel commented
looks great, after you verify we have all actions we want + test this in an deployed env. we can go ahead and push to master.
regarding our merge strategy - we use a squash merge strategy in our team so the history will be cleaner + cherry picking features / bisecting them will be easier.

2022-06-12 12:41 UTC, ozhey commented on plugins/sumo-logic/mask.yaml
> +    alias: CreateUser
No need for aliases, you can leave this one empty. If the autogenerated display name isn't clear, you can change it instead (`display_name` and not `alias`)

2022-06-12 12:41 UTC, ozhey commented on plugins/sumo-logic/mask.yaml
> +        alias: First Name
This is redundant, display names are generated automatically by putting spaces between words and camelcasing everything. Only add `alias` if you want it to be really different

2022-06-12 12:41 UTC, ozhey commented on plugins/sumo-logic/mask.yaml
> +        type: string
If the type is the same in the openapi definition, this is redundant. Only include it when you want to override the type defined in the openapi

2022-06-12 12:41 UTC, ozhey commented on plugins/sumo-logic/mask.yaml
> +        required: true
same here, if it's already required in the openapi, you don't need to specifiy it again.

2022-06-12 16:55 UTC, merged