TSK-5062 limit the http call by size and introduce outgoing rate limits
blinkops/blink-http pull request #160
Opened 2022-06-21 09:52 UTC by havivrosh

- add an outgoing rate limiter to the http plugin 
- every action (including all the plugins using the http plugin) should be counted as well
- limit per tenant the actions per min to be 1200 outgoing calls per min
- when a tenant hit this limit we fail the call and return an error 
- there is a sliding window so we always check the last min rate
-
- every http call will now be limited to max 2MB
- we will close the socket after 2MB
- we will return an error to the user that his payload is too large 
- we will not return the 2MB that we managed to read, its pointless because it could actually lead to wrong logic

2022-06-22 07:54 UTC, Idanraman requested changes

2022-06-22 07:54 UTC, Idanraman commented on implementation/requests/http.go
> +	if len(body) >= consts.LimitResponseSize {
When will this condition ever be met?

2022-06-22 07:54 UTC, Idanraman commented on implementation/requests/http.go
> +func validateTenantOutgoingRateLimit(ctx *plugin.ActionContext, limiter *limiter.Limiter) error {
When we'll scale up the amount of http plugins, this will stop being applicable. Not sure if we should do anything about it now, but worth keeping in mind that its a temporary solution

2022-06-22 07:54 UTC, Idanraman commented on consts/consts.go
> +	LimitResponseSize                     = 2 * 1024 * 1024 // 2 MB
Why not 5? 2 is a bit low

2022-06-22 07:54 UTC, Idanraman commented on implementation/requests/http.go
> +	ErrPayloadTooLarge = errors.New("payload too large, it exceeded the 2MB limit")
Lets use a const for the error message and define it in the same place as the limit size itself

2022-06-22 07:54 UTC, Idanraman commented on implementation/requests/http_test.go
> +	rawContext["tenant_id"] = "12121212"
Maybe lets add a test to show it really counts separately for each tenant, and not just sums all requests

2022-06-22 07:56 UTC, rimar-blink requested changes

2022-06-22 07:56 UTC, rimar-blink commented on consts/consts.go
> +	LimitResponseSize                     = 2 * 1024 * 1024 // 2 MB
This should be configurable

2022-06-22 07:56 UTC, rimar-blink commented on implementation/http_actions_test.go
> +	"github.com/blinkops/blink-http/implementation/requests"
you should reconfigure goland to format imports into 2 groups - golang and third parties

2022-06-22 09:16 UTC, blink-daniel commented on consts/consts.go
> +	LimitResponseSize                     = 2 * 1024 * 1024 // 2 MB
when we looked with @OmerGBlink , the response is duplicated at least 3 times by the time it goes to the UI. so 2 might be too high even, don't you think?

2022-06-22 09:51 UTC, havivrosh commented on implementation/requests/http.go
> +	if len(body) >= consts.LimitResponseSize {
in reality line 278 (ioutil.ReadAll(io.LimitReader(responseBody, consts.LimitResponseSize))) will read until it reaches the consts.LimitResponseSize and will return that in the body.
So the way to check is actually checking the body size. The LimitReader doesnt return an error when it reaches the limit.

2022-06-22 09:51 UTC, havivrosh commented on implementation/requests/http.go
> +func validateTenantOutgoingRateLimit(ctx *plugin.ActionContext, limiter *limiter.Limiter) error {
correct but I didnt want to make it complex.

2022-06-22 09:57 UTC, havivrosh commented on consts/consts.go
> +	LimitResponseSize                     = 2 * 1024 * 1024 // 2 MB
2MB is a really high number IMO.

2022-06-22 09:57 UTC, havivrosh commented on implementation/requests/http.go
> +	ErrPayloadTooLarge = errors.New("payload too large, it exceeded the 2MB limit")
k

2022-06-22 10:52 UTC, Idanraman commented on implementation/requests/http.go
> +	if len(body) >= consts.LimitResponseSize {
Ok, but how will the body become bigger than the limit if you've reached the limit?

2022-06-22 12:28 UTC, havivrosh commented on implementation/http_actions_test.go
> +	"github.com/blinkops/blink-http/implementation/requests"
k

2022-06-22 12:51 UTC, Idanraman commented on implementation/requests/http.go
> +	if len(body) >= consts.LimitResponseSize {
You said this if statement is here to be able to catch errors of oversized http requests since the overflow itself doesn't return an error, but Im not convinced it gets the result you claim... Maybe we can test it in an env.

2022-06-23 10:56 UTC, havivrosh commented on consts/consts.go
> +	LimitResponseSize                     = 2 * 1024 * 1024 // 2 MB
k

2022-06-23 11:13 UTC, Idanraman approved these changes

2022-06-23 11:20 UTC, rimar-blink approved these changes

2022-06-23 11:46 UTC, merged