Custom action tests for GCP Datadog Bitbucket
blinkops/blink-http pull request #49
Opened 2022-03-24 16:59 UTC by YakirOren

2022-03-24 19:33 UTC, ozhey requested changes

2022-03-24 19:33 UTC, ozhey commented on plugins/bitbucket/custom_actions_test.go
> +		// log.Println(workspaceID)
Forgot to remove?

2022-03-24 19:33 UTC, ozhey commented on plugins/datadog/custom_actions_test.go
> +	}
no test names?

2022-03-24 19:33 UTC, ozhey commented on plugins/datadog/custom_actions_test.go
> +		},
If you don't want to use the test name it's fine, but then just remove it

2022-03-24 19:33 UTC, ozhey commented on plugins/datadog/custom_actions_test.go
> +			name: "",
same heere

2022-03-24 19:33 UTC, ozhey commented on plugins/datadog/custom_actions_test.go
> +			name: "",
same

2022-03-24 19:33 UTC, ozhey commented on plugins/datadog/custom_actions_test.go
> +			name: "",
same

2022-03-24 19:33 UTC, ozhey commented on plugins/plugins.go
> +	"gcp":               gcp.GetNewGcpPlugin("https://admin.googleapis.com/"),
I don't think all endpoints go to to the admin subdomain. @shirleygordon-blink 
Should be googleapis.com like before

2022-03-27 07:07 UTC, YakirOren commented on plugins/plugins.go
> +	"gcp":               gcp.GetNewGcpPlugin("https://admin.googleapis.com/"),
The custom actions are for google workspace, which goes to the admin subdomain.

2022-03-27 07:57 UTC, ozhey commented on plugins/plugins.go
> +	"gcp":               gcp.GetNewGcpPlugin("https://admin.googleapis.com/"),
The default request url is being enforced on all actions using gcp connection, not only custom actions

2022-03-27 07:58 UTC, ozhey commented
you need to merge from main in order for the tests to pass

2022-03-27 08:48 UTC, ozhey approved these changes

2022-03-27 08:49 UTC, merged